version: '3.8'

services:

  backend:
    image: firme_backend:0.0.1
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - firme-network
    tty: true

  frontend:
    image: firme_frontend:0.0.1
    ports:
      - 4000:3000
    depends_on:
      - backend
    networks:
      - firme-network
    tty: true
  
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=firme_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata/data:/data/db:rw
      - ./dbdata/init.d:/docker-entrypoint-initdb.d
    networks:
      - firme-network

volumes:
  dbdata:

networks:
  firme-network:
    driver: bridge